export const ActionTypes = {
    SET_PHOTOS: "SET_PHOTOS",
    GET_PHOTO_BY_ID: "GET_PHOTO_BY_ID",
    UPLOAD_PHOTO: "UPLOAD_PHOTO",
    PUT_PHOTO: "PUT_PHOTO",
    DELETE_PHOTO: "DELETE_PHOTO",
    SET_GENRES: "SET_GENRES",
    PUT_GENRE: "PUT_GENRE",
    DELETE_GENRE: "DELETE_GENRE",
    ADD_GENRE: "ADD_GENRE"
};